general_config:
  method_name: surgical_tar
  target_modules:
    - dense_h_to_4h  # equivalent of gate_proj
  model_id: EleutherAI/pythia-14m
  # model_id: HuggingFaceTB/SmolLM-135M
  retain_set_name: wikitext
  forget_set_name: python
  unlearn_steps: 600
  batch_size: 16
  n_trials: 200
  normalize_grads: true
  # method specific
  unlearning_loss_fn: correct_logit_minus_avg
  use_masking: true
  train_adversary: true
  additional_param_name: null

relearn_config:
  relearn_steps: 300
  relearn_lr: 1.0e-4
  # relearn_lora_conf:
  #   target_modules: all-linear

hyperparams:
  adv_decay: [0.3, 1, false]
  adv_lr: [0.001, 0.01, true]
  fork_every_n_loops: [6, 42, false]
  retain_momentum: [0, 0.99, false]
  retaining_rate: [3.e-4, 3.e-3, true]
  unlearning_rate: [1.e-6, 1.e-3, true]
  additional_param: [0, 0, false]  # on default don't use this
  # todo repE retaining rate

variants:
  surgical_tar: {}

  # ! ablations
  no_r_momentum:
    retain_momentum: [0, 0, false]
  no_adv_decay:
    adv_decay: [1, 1, false]
  neg_entropy:
    unlearning_loss_fn: neg_entropy
  neg_cross_entropy:
    unlearning_loss_fn: neg_cross_entropy
  no_masking:
    use_masking: false
  no_adversary:
    train_adversary: false

  # ! optional components
  f_momentum:
    additional_param_name: forget_momentum
    additional_param: [0, 1, false]
  adv_update:
    additional_param_name: adv_update
    additional_param: [0, 1, false]
  clip_at:
    additional_param_name: clip_at
    additional_param: [-10, 10, false]
  discard_growing_weights:
    additional_param_name: discard_growing_weights
    additional_param: [0, 1, false]
  # todo full + repE loss
  
  surgical_tar_lora:
    method_name: surgical_tar_lora
    lora_amount: 1
    lora_rank: 8
    adv_lr: [0.001, 0.05, true]  # LoRA can have a higher learning rate
  tar:
    method_name: tar
    adv_decay: [1, 1, false]  # has no effect here, so set it to 1
    # todo needs also repE loss
    # todo grad norm
    # todo target modules?
  # todo TAR that can use safeguarding step?
    
  # circuit_breaker_without_lora:
  #   method_name: circuit_breaker_without_lora
  #   # todo grad norm
  #   # todo target modules?

    # retaining_rate: [5.e-4, 5.e-3, true]

  # circuit_breaker:
  #   method_name: circuit_breaker
  #   # todo grad norm
  #   # todo target modules?
  #   # note: it's trained without LoRA as was the original circuit breaker paper
  #   forget_momentum: [0, 0, false]
  #   retain_momentum: [0, 0, false]
  #   adv_decay: [1, 1, false]
  #   adv_update: [0, 0, false]
  #   use_masking: false
  #   train_adversary: false
  
  # todo only decrease weights
