general_config:
  method_name: surgical_tar
  target_modules:
    - up_proj
  unlearning_loss_fn: correct_logit_minus_avg
  # model_id: EleutherAI/pythia-14m
  model_id: HuggingFaceTB/SmolLM-135M
  retain_set_name: wikitext
  forget_set_name: python
  unlearn_steps: 240
  batch_size: 16
  n_trials: 50
  # method specific
  use_masking: true
  use_normalization: true
  train_adversary: true
  additional_param_name: null

relearn_config:
  relearn_steps: 120
  relearn_lr: 1.0e-4
  # for Smol I checked that no-LoRA relearns better
  # relearn_lora_conf:
  #   target_modules: all-linear

hyperparams:
  adv_decay: [0.4, 1, false]
  adv_lr: [0.001, 0.006, true]
  fork_every_n_loops: [6, 42, false]
  retain_momentum_decay: [0, 0.99, false]
  retaining_rate: [5.e-4, 5.e-3, true]
  unlearning_rate: [0.05, 5, true]

variants:
  up_proj:
    target_modules:
      - up_proj
  down_proj:
    target_modules:
      - down_proj
  gate_proj:
    target_modules:
      - gate_proj
  q_proj:
    target_modules:
      - q_proj
  k_proj:
    target_modules:
      - k_proj
  v_proj:
    target_modules:
      - k_proj
  o_proj:
    target_modules:
      - o_proj
  all_linear:
    target_modules:
      - up_proj
      - down_proj
      - gate_proj
      - q_proj
      - k_proj
      - v_proj
      - o_proj
  mlp:
    target_modules:
      - up_proj
      - down_proj
      - gate_proj
  attn:
    target_modules:
      - q_proj
      - k_proj
      - v_proj
      - o_proj
  mlp_and_o_proj:
    target_modules:
      - up_proj
      - down_proj
      - gate_proj
      - o_proj
  mlp_and_o_proj_unnormalized:
    target_modules:
      - up_proj
      - down_proj
      - gate_proj
      - o_proj
    use_normalization: false
    # update_scale_factor: 0.1